Import-Module G:\PS\PSMap\src\DGML\DgmlDirectedGraph.psd1 -Force

#todo https://github.com/merijndejonge/Structurizr.Dgml
# https://ceyhunciper.wordpress.com/

$Graph= New-DgmlGraph -Title 'Test'
$Nodes= New-DgmlNodeList
$Links= New-DgmlLinkList 

Add-DgmlNode -Nodes $Nodes -Properties @{id='a'}
 #Allow duplicate data, no exception
 #Add-DgmlNode -Nodes $Nodes @{id='a'}
Add-DgmlNode -Nodes $Nodes -Properties @{id='b'}
Add-DgmlNode -Nodes $Nodes -Properties @{id='c'}
    #Todo transforme .svg de vscode-icon en .ico
Add-DgmlNode -Nodes $Nodes -Properties @{id='E';Group="Expanded";Shape="$PSscriptRoot\file_type_powershell.svg"} #;Shape="c:\temp\Succes.png"}
Add-DgmlNode -Nodes $Nodes -Properties @{id='F';Group="Collapsed";Shape="$PSscriptRoot\file_type_powershell_psm.svg"}

#todo add test to find duplicate node
# $Nodes.exists(predicate)

Add-DgmlLink -Links $Links -Properties @{Source='a';Target='b'}
Add-DgmlLink -Links $Links -Properties @{Source='a';Target='c'}
Add-DgmlLink -Links $Links -Properties @{Source='a';Target='a'}
 #Allow duplicate data, no exception
 #Add-DgmlLink -Links $Links@{Source='a';Target='b'}

$Graph.Nodes=$Nodes
$Graph.Links=$Links
#Convert a class generated by Xsd.Exe
#save with .Dgml extension fo VS
XMLObject\ConvertTo-XML -Object $Graph -Filename 'C:\Temp\dgml.xml' -SerializedType 'DgmlUtils.DirectedGraph' -targetNamespace 'http://schemas.microsoft.com/vs/2009/dgml'

#dgmlimage Nuget Package
#create C:\temp\Dgml.png
& "$PSscriptRoot\dgmlimage\DgmlImage.exe" C:\temp\Dgml.xml /out:C:\temp
Invoke-Item C:\temp\dgml.png
